name: Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Install Dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Run linter
        run: |
          source .venv/bin/activate
          ruff check src tests

      - name: Check formatting
        run: |
          source .venv/bin/activate
          ruff format --check src tests

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/ -v --cov=src --cov-report=term-missing
